### PR TITLE
Xiaomi philips downlights

### PR DESCRIPTION
**Pull request by luckypoppy**
Because I had problems controlling my new LED spots (Xiaomi/Philips ZhiRui Downlights), I copied your yeelight LED strip files to a new set of files to create a new node-red device inside your node. The reason for this: power and brightness control was working fine, but only the temperature control was not working because the "cct" attribute was missing.

This is my first github fork / branch / pull experience, just like creating new node-red nodes. If I have forgotten something or there's something I can do, please let me know.

### CODE REVIEW

**Comment by YinHangCode** [comment]
校验一下代码里的tab换成四个空格。
这个设备我没有，没法测试，你测试没问题的话我就合并。

**Review by luckypoppy — COMMENTED** [review]
I have tested the change and everything works fine for me.

**Comment by 876310253** [comment]
用中文，你也好意思？？

**Comment by luckypoppy** [comment]
我测试了设备上的变化，一切正常。 我来自荷兰，我的中文不是很好;）

**Comment by YinHangCode** [comment]
Sorry, I thought you were Chinese at first, so I replied to re in Chinese.
Actually your Chinese is pretty good, cause you can understand my words.
I'll merge your code later, Thank you to submitting, Friendly greeting from China.

**Comment by bbkinghun** [comment]
Hi

When will the cct command work?

Thanks

**Comment by YinHangCode** [comment]
@luckypoppy 
Is the model "philips.light.downlight" of this device?

**Comment by luckypoppy** [comment]
> @luckypoppy
> Is the model "philips.light.downlight" of this device?

Name/Model: Xiaomi Philips / Zhirui / Adjustable Color Temperature Downlight 

Example: https://www.xiaomitoday.com/xiaomi-philips-zhirui-adjustable-color-temperature-downlight/

**Comment by bbkinghun** [comment]
Hi
Yes
Xiaomi Philips Zhirui Adjustable Color Temperature Downlight

Problem solved

I change json rgb to cct 

Thanks

**Comment by bbkinghun** [comment]
Hi

The node you made is working, but I want to schedule "sunset, sunrise" unfortunately I don't know why it doesn't work. I try bigtimer send on-off to function node.

Is it possible to send a command to websocket? "I use Node Red" 
Can you help me how to create a line of lamp switching commands?
 
this command is incorrect:

set cmd:{"Downlight1"},deviceIP: { value: "192.168.1.129"},deviceToken: { value: "123456789xxxxxx"},deviceSyncInterval: { value: "0",},attributes: {"power": "on","bright":"100","cct":"100"}


Thanks

**Pull request merged**
